### ISSUE TITLE
MRI changes RelevantProperties as like suggested refactoring have already been applied

### ISSUE THREAD

**Issue by Ivan-Veselov** [ml-in-programming/ArchitectureReloaded#69]
https://github.com/ml-in-programming/ArchitectureReloaded/blob/0e72c47cbc8fc73cd539b7543a9235aa54a87b3b/src/main/java/org/ml_methods_group/algorithm/MRI.java#L124

Current logic of MRI algorithm as I see it is that right after finding new possible refactoring it changes RelevantProperties as like this refactoring has been applied. Looks very suspicious. Is this really what it should do?

**Comment by jzuken** [comment]
Yep, works like this by design. Did not meet our expectations, so going to be removed soon.
